apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-{{.build.nameSuffix}}
  namespace: {{.build.namespace}}
spec:
  params:
  - name: url
    value: {{.build.push.toRegistry}}
  type: image
